# Default values for zcspm-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ZCSPM Agent details
namespace: zcspm

# ZCSPM Agent configuration details
clusterName: "<cluster_name>"
licenseId: "<zcspm_licenseId>"
accountId: "<zcspm_accountId>"
zcspmApiAppId: "<zcspm_ApiAppId>"

clusterHosting: "AKS"
zcspmEnvironment: "prod"

# Coudneeti API and ApiApp key/secrets
zcspmAPIKey: "<zcspmAPIKey>"
zcspmAPIAppSecret: "<zcspmAPIAppSecret>"

images:
# Default image pull policy for all images
  imagePullPolicy: Always

# Details of images being used in the chart 
  zcspmAgentImage: 
    repository: cloudneeticorp/zcspm-agent
    tag: "2.11"

  kubebenchImage: 
    repository: aquasec/kube-bench
    tag: "0.6.0"

cronjob:
  # At 12:00 every day
  schedule: "0 12 * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: "3"
  successfulJobsHistoryLimit: "2"
