# Default values for cloudneeti-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Cloudneeti Agent details
namespace: cloudneeti

# Cloudneeti Agent configuration details
clusterName: "<cluster_name>"
licenseId: "<cloudneeti_licenseId>"
accountId: "<cloudneeti_accountId>"
cloudneetiEnvironment: "<environment>"
cloudneetiApiAppId: "<cloudneeti_ApiAppId>"
clusterHosting: "<AKS/AKS-Engine/EKS/VM-Based/EC2-Instance-Based>"
  
# Coudneeti API and ApiApp key/secrets
cloudneetiAPIKey: "<cloudneetiAPIKey>"
cloudneetiAPIAppSecret: "<cloudneetiAPIAppSecret>"

image:
  repository: cloudneeticorp/cloudneeti-agent
  tag: 2.6
  pullPolicy: IfNotPresent

cronjob:
  # At 12:00 every day
  schedule: "0 12 * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: "3"
  successfulJobsHistoryLimit: "2"